### ISSUE TITLE
Todo list for API for AP manager (cloudified AP Predict)

### ISSUE THREAD

**Issue by MauriceHendrix** [CardiacModelling/ap-nimbus-app-manager#1]
- [ ] Bring over code from AP Nimbus repository
- [ ] Set up license, .gitignore, readme.md
- [ ] Set up automated tests
- [ ] Add ability to deal with cellml & pk data file uploads
- [ ] Further development
    - [ ] Add AP predict version to api
    - [ ] consider how ap returns results

**Comment by flawmop** [comment]
This is call completed, so closing.
